### ISSUE TITLE
Serverside - force quality settings

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#176]
**Is your feature request related to a problem? Please describe.**
I want to forcefully enable "lossless" as the quality mode and enable "webrtc_udp "

**Describe the solution you'd like**
It would be great to be able to just pass this as a variable to the vncserver- command.

**Comment by ne0YT** [comment]
I tried with the standard config file under:
/etc/kasmvnc/kasmvnc.yaml

while only changing:
runtime_configuration:
  allow_client_to_override_kasm_server_settings: false
  allow_override_standard_vnc_server_settings: false
  
  I can still set whatever I want when connecting from the client.

**Comment by ne0YT** [comment]
@mmcclaskey 
no way to force or just predefine "lossless" ?

**Comment by ledestin** [comment]
In order to lock-in lossless, besides the options you've changed, you need to change `encoding.video_encoding_mode.jpeg_quality`, etc in a server config.

UI lets you set anything, but it doesn't change stream quality settings you set in server config (with client overrides disabled).

I'll cover WebRTC UDP later.

**Comment by ne0YT** [comment]
> In order to lock-in lossless, besides the options you've changed, you need to change `encoding.video_encoding_mode.jpeg_quality`, etc in a server config.
> 
> UI lets you set anything, but it doesn't change stream quality settings you set in server config (with client overrides disabled).
> 
> I'll cover WebRTC UDP later.

Can you post the example config to represent lossless?

**Comment by ne0YT** [comment]
> In order to lock-in lossless, besides the options you've changed, you need to change `encoding.video_encoding_mode.jpeg_quality`, etc in a server config.
> 
> UI lets you set anything, but it doesn't change stream quality settings you set in server config (with client overrides disabled).
> 
> I'll cover WebRTC UDP later.

hey there :)
any update?

**Comment by ne0YT** [comment]
@ledestin hey there, it would be very nice if you could help me out as I don't get what to set.
if you could share the part of the config it would be really great :)

**Comment by ne0YT** [comment]
@ledestin I really cannot figure it out.
please help me out :)

**Comment by ne0YT** [comment]
@mmcclaskey maybe you can help?

**Comment by ne0YT** [comment]
@ledestin @mmcclaskey @lyarwood @koying @lhchavez 
please any way to force this?

**Comment by john-deng** [comment]
@ne0YT did you make any progress on this issue?

**Comment by ne0YT** [comment]
@john-deng sadly not at all. You're trying the same?

**Comment by john-deng** [comment]
@ne0YT Yes, I am. Not only this issue, but a lot more. I think we may contribute to this project, and things will get much easier if we can get some help from Kasmtech, e.g. hold the community meeting to discuss key features and issues. @mmcclaskey

**Comment by mmcclaskey** [comment]
This setting does not restrict everything. Current logging does not provide any feedback explicitly on what settings are applied or not applied when the client sends the changes.

@clbr, could you please do the following
1. When logging is set to 100, log settings that are sent by the client and whether they were applied or ignored.
2. Can you provide a list of what settings the server will ignore from the client when `-IgnoreClientSettingsKasm 1` is passed to Xvnc. I can then document this.

Initial testing does show that video mode is not altered by the client changing the Preset mode. When the preset is set to Extreme, it should disable video mode and that is not happening as expected. Once the above two items are addressed we can fully test that all settings that should be blocked are being blocked.

```yaml  
  runtime_configuration:
    allow_client_to_override_kasm_server_settings: false

  logging:
    log_writer_name: all
    log_dest: logfile
    # 0 - minimal verbosity, 100 - most verbose
    level: 100

  encoding:
    max_frame_rate: 60
    full_frame_updates: none
    rect_encoding_mode:
      min_quality: 7
      max_quality: 8
      consider_lossless_quality: 10
      rectangle_compress_threads: auto

    video_encoding_mode:
      jpeg_quality: -1
      webp_quality: -1
      max_resolution:
        width: 1920
        height: 1080
      enter_video_encoding_mode:
        time_threshold: 5
        area_threshold: 45%
      exit_video_encoding_mode:
        time_threshold: 3
      logging:
        level: off
      scaling_algorithm: progressive_bilinear
```
