### ISSUE TITLE
start without ssl does not work when setting: network.ssl.require_ssl to false in /etc/kasmvnc/kasmvnc.yaml

### ISSUE THREAD

**Issue by ne0YT** [kasmtech/KasmVNC#181]
**Describe the bug**
I set:
```
runtime_configuration:
  allow_client_to_override_kasm_server_settings: false
  allow_override_standard_vnc_server_settings: false

network:
  ssl:
    require_ssl: false
```

inside:
/etc/kasmvnc/kasmvnc.yaml

and started kasmvnc
it will still start it with https://

I verified that the file generally gets checked, as when I configure something wrong in /etc/kasmvnc/kasmvnc.yaml, it will tell me that.

**System Description**
Provide the output of 
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.

Provide the output of this command.
```
Xvnc KasmVNC 1.1.0.446d03d4792f35e2981e566241b7f31b7e0d5207 - built Aug 21 2023 17:57:32
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```
