### ISSUE TITLE
Problems with Apache Reverse Proxy

### ISSUE THREAD

**Issue by felix-sterzelmaier-concat** [kasmtech/KasmVNC#197]
I am running a server in my local network which has many services running in docker. I want to add KasmVNC to these services. Here is my Docker-Compose File:

```
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - CUSTOM_USER=xxx
      - PASSWORD=xxx
    volumes:
      - /data/webtop2/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 8007:3000
      - 8008:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "4gb" #optional
    restart: unless-stopped
```

From my client in my local network i am able to reach http://192.168.178.75:8007/ and https://192.168.178.75:8008/. Everything is working fine so far. Now i want to make this service available behind a reverse proxy. I used the documentation here: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#example-apache-config
This is my Apache config:

```
<VirtualHost *:443>
    ServerName xxx
    # SSL
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    # Websocket upgrade
    RewriteEngine on
    RewriteCond ${HTTP:Upgrade} websocket [NC]
    RewriteCond ${HTTP:Connection} upgrade [NC]
    RewriteRule .* "wss://127.0.0.1:8008/$1" [P,L]
    # Proxy
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyPreserveHost on
    ProxyPass / https://127.0.0.1:8008/
    ProxyPassReverse / https://127.0.0.1:8008/
    ProxyRequests off
</VirtualHost>
```
I have a DNS-Record to my router which is forwarded (using NAT) to the docker host. Let's assume the DNS-Record is example.com. When opening https://example.com i see this:

![a](https://github.com/kasmtech/KasmVNC/assets/148772869/0b8d11ab-c68b-4c57-b546-c35b31f0009e)

![b](https://github.com/kasmtech/KasmVNC/assets/148772869/c2ece97a-68f9-4bb6-b9d0-67f94a8f0b06)

![c](https://github.com/kasmtech/KasmVNC/assets/148772869/bc9b6cc8-48f2-4800-8db0-5a38daa6ec3f)

OS: Ubuntu Server 22.04 LTS 64bit

Is the Documentation https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#example-apache-config still up to date? Can you give me some hints how to fix this problem?
