### ISSUE TITLE
[BUG]: Cannot access VNC after set concurrent_connections_prompt

### ISSUE THREAD

**Issue by namlh-eureka** [kasmtech/KasmVNC#242]
**Describe the bug**
Cannot access VNC after set concurrent_connections_prompt

**System Description**
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
Linux vnc-trial-1 6.5.0-1018-aws #18~22.04.1-Ubuntu SMP Fri Apr  5 17:44:33 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**KasmVNC Details**
```
Xvnc KasmVNC 1.2.0.2af2e661e9906b5778644f6e2fbe1f51cebb337a - built Sep 13 2023 23:49:36
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
1. Set ~/.vnc/kasmvnc.yaml like this
```
desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: false
  pixel_depth: 24

network:
  ssl:
    require_ssl: false

user_session:
  session_type: exclusive
  new_session_disconnects_existing_exclusive_session: true 
  concurrent_connections_prompt: true
  concurrent_connections_prompt_timeout: 30

logging:
  log_writer_name: all
  log_dest: logfile
  level: 100

server:
  http:
    headers:
      - Access-Control-Allow-Origin=*
```
2. Start kasmvnc as systemd service
3. Go to `http://{ip}:{port}`
4. Wait very long time -> browser like this
![image](https://github.com/kasmtech/KasmVNC/assets/117136792/80e46efa-4dea-4e38-895d-c4ec993bd85d)

**Expected behavior**
Can normally access VNC

**Browser**
Browser chrome
