### ISSUE TITLE
Connection disconnected when running KasmVNC on default user

### ISSUE THREAD

**Issue by saikotek** [kasmtech/KasmVNC#307]
**Describe the bug**
I have proxmox host that runs xubuntu VM and the traffic is going through NAT like this:
Internet -> public_ip:8444 -> [DNAT] -> 10.0.0.2:8444 (VM)
10.0.0.2:8444 (VM) -> [SNAT/MASQUERADE] -> public_ip -> Client

and nginx works, so no problem there. But trying to run kasmVNC and connecting through Chrome first shows that it's connected after which instantly it says "Disconnected", in F12 in Chrome I see some 401 Unauthorized requests.
![chrome_esEZwHnXLF](https://github.com/user-attachments/assets/d1b42579-b248-42ba-b037-454ce6933198)

Curiously in firefox all requests are OK (change protocols to websocket request 101 is also OK)
![9icKx80TdF](https://github.com/user-attachments/assets/70110021-11e0-4c21-a27d-200b81d80d70)
but it still gets disconnected.

This is failing log:
[vnc-log.log](https://github.com/user-attachments/files/18220376/vnc-log.log)

So I tried creating new user, copying kasmvnc.yaml and running vncserver there and..it looks like it works now!
I'm attaching working log
[working-log-other-user.log](https://github.com/user-attachments/files/18220378/working-log-other-user.log)
Looks like there are still some errors there, but it works..

This is process tree dump:
[process_tree.txt](https://github.com/user-attachments/files/18220388/process_tree.txt)
Note that default user is 'u' and the new one is 'rem' and there I ran vncserver successfully.

**System Description**
```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

Linux 0polaroid34 6.8.0-39-generic #
39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**KasmVNC Details**
Provide the filename of the package you installed KasmVNC with. The filename includes important details like the OS, architecture, and commit sha.
`kasmvncserver_noble_1.3.3_amd64.deb`

Provide the output of this command.
```bash
Xvnc -version
```
`XVnc: command not found`
when directly calling:
```
 /usr/bin/Xvnc -version

Xvnc KasmVNC 1.3.3.0ebbbc6412e131092308cc1ce10b9d106e3b4e05 - built Oct 30 2024 14:13:20
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12008000, The X.Org Foundation
```

**To Reproduce**
Steps to reproduce the behavior (for non-installation issues):
1. Install kasmvnc on xubuntu 24
2. Run vncserver no default user
3. Try to connect through chrome

**Expected behavior**
Should connect without issues.

**Browser**
 - Device: PC
 - OS: Windows 11
 - Browser Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Firefox 133.0.3 (64-bit)

**Additional context**
I had to do `kasmvnc.yaml` settings like this:
```
logging:
  log_writer_name: all
  log_dest: logfile
  level: 100

network:
  protocol: http
  interface: 0.0.0.0
  websocket_port: 8444 
  use_ipv4: true
  use_ipv6: true
  udp:
    public_ip: auto
    port: 8444
    stun_server: auto
  ssl:
    pem_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    pem_key: /etc/ssl/private/ssl-cert-snakeoil.key
    require_ssl: true
  # unix_relay:
  #   name:
  #   path:

security:
  brute_force_protection:
    blacklist_threshold: 0
    blacklist_timeout: 0
```
because with brute force security it blocks me right away because it looks like the connection is dropping many times in a row.
