### ISSUE TITLE
View only session without control bar access

### ISSUE THREAD

**Issue by Nivg** [kasmtech/KasmVNC#322]
Hello, I’ve been working on this fantastic project to expose remote desktops to users as view-only, with our own hosting.

However, I’m facing an issue where I can’t completely disable or hide the control bar on the left side of the desktop. I’ve managed to prevent users from accessing the desktop through certain configurations, but I’m unable to eliminate the control bar entirely.

I’m wondering if I’m overlooking something or if this project wasn’t intended for this specific use case of sharing a desktop view with users, but not allowing them to interact with it (similar to sharing a screen during a Zoom call). 

Those are my simple settings (am using the firefox image):
Dockerfile:
```
FROM kasmweb/firefox:1.16.0

USER root

# Install required tools
RUN apt-get update && apt-get install -y \
  xdotool \
  x11-utils \
  python3 \
  && rm -rf /var/lib/apt/lists/*

# Add sudo access for kasm-user
RUN echo "kasm-user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Copy and set permissions for configuration files
COPY kasmvnc.yaml /etc/kasmvnc/kasmvnc.yaml
RUN chown -R 1000:1000 /etc/kasmvnc/kasmvnc.yaml

# Switch back to kasm-user
USER 1000 
```

kasmvnc.yaml:
```
desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: false
  pixel_depth: 24

network:
  protocol: http
  interface: 0.0.0.0
  websocket_port: 6901
  use_ipv4: true
  use_ipv6: false
  ssl:
    pem_certificate: ${HOME}/.vnc/self.pem
    pem_key: ${HOME}/.vnc/self.pem
    require_ssl: true

logging:
  level: info

security:
  brute_force_protection:
    blacklist_threshold: 0
    blacklist_timeout: 0

pointer:
  enabled: false

keyboard:
  raw_keyboard: false
  ignore_numlock: false

runtime_configuration:
  allow_client_to_override_kasm_server_settings: false

encoding:
  max_frame_rate: 60
  video_encoding_mode:
    max_resolution:
      width: 1920
      height: 1080
```

docker-composer.yml:
```
version: "3.8"

services:
  firefox:
    build:
      context: .
      dockerfile: Dockerfile.firefox
    container_name: kasm-firefox
    shm_size: 512m
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=password
```
