### ISSUE TITLE
disable basicauth

### ISSUE THREAD

**Issue by solipsist01** [kasmtech/KasmVNC#96]
Hello.

I don't want the kasm desktop container to handle authentication, as I'm using a traefik reverse proxy with forward authentication.
How can i disable VNC authentication of the desktop image ?

```
version: "3.5"
services:
  kasm:
    container_name: kasm
    environment:
      - VNC_PW=pleaseletmedisablethis:)
      - TZ=${TZ}
    image: kasmweb/desktop:1.10.0-rolling
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.http.routers.kasm.entrypoints=websecure"
      - "traefik.http.routers.kasm.tls.certresolver=cloudflare"
      - "traefik.http.routers.kasm.middlewares=cloudflare@docker, keycloak@docker"
      - "traefik.http.services.kasm.loadbalancer.server.scheme=https"
      - "traefik.http.services.kasm.loadbalancer.server.port=6901"
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}
```

**Comment by mmcclaskey** [comment]
KasmVNC supports multiple users on a single session and different permission sets for each user. This allows for use cases like training, where the instructor has read/write access and the students have read/only access. These permissions can be changed via API. Only the owner can change permissions for users. All that to say, it is not possible to simply disable basic auth, because then KasmVNC has no idea who the connection belongs to and what permissions to apply.

Suggestion, configure your reverse proxy to inject the "Authorization" header. The username and password are base64 encoded, so it is a little bit more involved. The following post covers it...

https://stackoverflow.com/questions/43821612/authorization-header-in-nginx-for-proxying-to-basic-auth-backend-doest-work

**Comment by solipsist01** [comment]
Thank you very much, this solved my problem.
If anyone in the future reads this, this was the solution to disable this in Traefik.

In a bash terminal:

```
echo -n "kasm_user:yourmostawesomepasswordhere" | base64
a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ==
```

Your docker-compose.yml

```

version: "3.5"
services:
  kasm:
    container_name: kasm
    environment:
      - VNC_PW=yourmostawesomepasswordhere
      - TZ=${TZ}
    image: kasmweb/desktop:1.10.0-rolling
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.http.middlewares.kasmauth.headers.customrequestheaders.Authorization=Basic a2FzbV91c2VyOnlvdXJtb3N0YXdlc29tZXBhc3N3b3JkaGVyZQ=="
      - "traefik.http.routers.kasm.entrypoints=websecure"
      - "traefik.http.routers.kasm.tls.certresolver=cloudflare"
      - "traefik.http.routers.kasm.middlewares=cloudflare@docker, keycloak@docker, kasmauth@docker"
      - "traefik.http.services.kasm.loadbalancer.server.scheme=https"
      - "traefik.http.services.kasm.loadbalancer.server.port=6901"
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}

networks: 
  core:
    name: ${NETWORK}
```
